version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    allow:
      - dependency-type: direct
    reviewers:
      - "ePages-de/team-x"
      - "ePages-de/team-white"
    cooldown:
      default-days: 5
