name: 'Package helm chart'
description: 'An action to package the helm chart using the generated rabbitmq bindings.'

inputs:
  build-timestamp:
    description: 'The build timestamp in the "yyyyMMddHHmmss" format. Ex: 20220106100059'
    required: true
  project-chart-name:
    description: 'The chart name of this project (without ng- prefix). Ex: product-management'
    required: true
  helm-repo-url:
    description: 'The repo URL'
    required: true
    default: https://epagesbeyond.jfrog.io/epagesbeyond/beyond-helm-local
  artifactory-username:
    description: 'The username to access the artifactory helm repo.'
    required: true
  artifactory-password:
    description: 'The password to access the artifactory helm repo.'
    required: true

outputs:
  chart-version: 
    description: 'The version of the chart published'

runs:
  using: 'docker'
  image: 'Dockerfile' # Publish this as a docker image and use it here so that it does not need to be build everytime
  args:
    - ${{ inputs.build-timestamp }}
    - ${{ inputs.project-chart-name }}
    - ${{ inputs.helm-repo-url }}
    - ${{ inputs.artifactory-username }}
    - ${{ inputs.artifactory-password }}