name: 'Package helm chart'
description: 'A composite action to package and publish the helm chart of ng services.'
author: 'Roberto Welzel Filho <rwelzel@epages.com>'

inputs:
  build-timestamp:
    description: 'The build timestamp in the "yyyyMMddHHmmss" format. Ex: 20220106100059'
    required: true
  project-chart-name:
    description: 'The chart name of this project (without ng- prefix). Ex: product-management'
    required: true
  helm-repo-url:
    description: 'The repo URL'
    required: true
  artifactory-username:
    description: 'The username to access the artifactory helm repo.'
    required: true
  artifactory-password:
    description: 'The password to access the artifactory helm repo.'
    required: true

outputs:
  chart-version:
    description: 'The version of the chart published'
    value: ${{ steps.package-helm-chart.outputs.chart-version }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Download generated messaging helm values ⬇️
      uses: actions/download-artifact@v2
      with:
        name: message-artifact-values
        path: build/message-artifacts-helm
    - id: package-helm-chart
      uses: docker://epages/ng-action-package-helm-chart:develop
      with:
        args: >-
          ${{ inputs.build-timestamp }}
          ${{ inputs.project-chart-name }}
          ${{ inputs.helm-repo-url }}
          ${{ inputs.artifactory-username }}
          ${{ inputs.artifactory-password }}
